package ca.kittle.models.integrations.creature

import ca.kittle.models.Swarm
import ca.kittle.models.integrations.Source
import kotlinx.serialization.Serializable

@Serializable
data class Creature (

	val collectionUserId : Int,
	val isReleased : Boolean,
	val url : String,
	val conditionImmunitiesHtml : String,
	val sensesHtml : String,
	val skillsHtml : String,
	val stats : List<Stat>,
	val senses : List<Sense>,
	val savingThrows : List<Save>,
	val skills : List<Skill>,
	val languages : List<Language>,
	val hitPointDice : HitPointDice,
	val swarm : Swarm?,
	val movements : List<Movement>,
	val homebrewStatus : Int,
	val id : Int,
	val entityTypeId : Int,
	val name : String,
	val alignmentId : Int?,
	val sizeId : Int,
	val typeId : Int,
	val armorClass : Int,
	val armorClassDescription : String,
	val averageHitPoints : Int,
	val passivePerception : Int,
	val isHomebrew : Boolean,
	val challengeRatingId : Int,
	val sourceId : Int?,
	val sourcePageNumber : Int?,
	val isLegendary : Boolean,
	val isMythic : Boolean,
	val hasLair : Boolean,
	val avatarUrl : String,
	val largeAvatarUrl : String?,
	val basicAvatarUrl : String?,
	val version : String?,
	val subTypes : List<Int>,
	val environments : List<Int>,
	val tags : List<String>,
	val sources : List<Source>,
	val damageAdjustments : List<Int>,
	val conditionImmunities : List<Int>,
	val specialTraitsDescription : String,
	val actionsDescription : String,
	val reactionsDescription : String,
	val legendaryActionsDescription : String,
	val mythicActionsDescription : String?,
	val bonusActionsDescription : String?,
	val characteristicsDescription : String,
	val lairDescription : String,
	val languageDescription : String?,
	val languageNote : String?,
	val hideCr : Boolean,
	val isLegacy : Boolean
)
